[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "publicsuffixlist"
dynamic = ["version"]
description = "publicsuffixlist implement"
readme = "README.md"
requires-python = ">=3.8"
license = "MPL-2.0"
license-files = ["LICENSE"]
authors = [
    { name = "ko-zu", email = "causeless@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Internet :: Name Service (DNS)",
    "Topic :: Text Processing :: Filters",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/ko-zu/psl"
Repository = "https://github.com/ko-zu/psl"

[project.optional-dependencies]
update = ["requests"]
readme = ["pandoc"]

[project.scripts]
publicsuffixlist-download = "publicsuffixlist.update:updatePSL"

[dependency-groups]
dev = [
    "requests",
]

[tool.hatch.version]
path = "publicsuffixlist/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["publicsuffixlist"]

[tool.hatch.build.targets.sdist]
include = [
    "/publicsuffixlist",
    "/README.md",
    "/LICENSE",
]
